### ISSUE TITLE
Check if directory size exceeds upload limits for the chosen pinning services before trying to upload

### ISSUE THREAD

**Issue by agentofuser** [agentofuser/ipfs-deploy#54]
- Infura: 100MB https://community.infura.io/t/is-there-a-file-size-limit-for-files-attached-to-ipfs-infura-io/61/2
- Pinata: 1GB https://github.com/agentofuser/ipfs-deploy/issues/52#issuecomment-502366577

ref #52

**Comment by ekollof** [comment]
$ ipd -p pinata
ℹ 🤔 No path argument specified. Looking for common ones…
✔ 📂 Found local public directory. Deploying that.
✔ 🚚 public weighs 133.3 MiB.
⠸ 📠 Uploading and pinning via https to pinata.cloud…(node:16473) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/usr/local/share/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/share/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/share/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:16473) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16473) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the
future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ 📠 Uploading and pinning via https to pinata.cloud…^C

(keeps retrying)

**Comment by agentofuser** [comment]
Odd that it didn't capture the error to display it properly. Does trying with a small upload give the same error?

**Comment by ekollof** [comment]
Nope, that completes fine.
